//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: c_table_cfg_global.proto
// Note: requires additional types generated from: table_common.proto
namespace TABLE
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFG_GLOBAL")]
  public partial class CFG_GLOBAL : global::ProtoBuf.IExtensible
  {
    public CFG_GLOBAL() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }

    private string _remarks;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"remarks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string remarks
    {
      get { return _remarks?? ""; }
      set { _remarks = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool remarksSpecified
    {
      get { return _remarks != null; }
      set { if (value == (_remarks== null)) _remarks = value ? remarks : (string)null; }
    }
    private bool ShouldSerializeremarks() { return remarksSpecified; }
    private void Resetremarks() { remarksSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFG_GLOBALARRAY")]
  public partial class CFG_GLOBALARRAY : global::ProtoBuf.IExtensible
  {
    public CFG_GLOBALARRAY() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.CFG_GLOBAL> _rows = new global::System.Collections.Generic.List<TABLE.CFG_GLOBAL>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rows", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.CFG_GLOBAL> rows
    {
      get { return _rows; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}