//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: table_common.proto
namespace TABLE
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemDrop")]
  public partial class ItemDrop : global::ProtoBuf.IExtensible
  {
    public ItemDrop() {}
    

    private TABLE.ItemDrop.ProbType? _prob_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prob_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public TABLE.ItemDrop.ProbType prob_type
    {
      get { return _prob_type?? TABLE.ItemDrop.ProbType.PROB_TYPE_SPECIFIED; }
      set { _prob_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool prob_typeSpecified
    {
      get { return _prob_type != null; }
      set { if (value == (_prob_type== null)) _prob_type = value ? prob_type : (TABLE.ItemDrop.ProbType?)null; }
    }
    private bool ShouldSerializeprob_type() { return prob_typeSpecified; }
    private void Resetprob_type() { prob_typeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<TABLE.ItemDrop.Drop> _drop_list = new global::System.Collections.Generic.List<TABLE.ItemDrop.Drop>();
    [global::ProtoBuf.ProtoMember(2, Name=@"drop_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.ItemDrop.Drop> drop_list
    {
      get { return _drop_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Drop")]
  public partial class Drop : global::ProtoBuf.IExtensible
  {
    public Drop() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }

    private uint? _prob;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"prob", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prob
    {
      get { return _prob?? default(uint); }
      set { _prob = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool probSpecified
    {
      get { return _prob != null; }
      set { if (value == (_prob== null)) _prob = value ? prob : (uint?)null; }
    }
    private bool ShouldSerializeprob() { return probSpecified; }
    private void Resetprob() { probSpecified = false; }
    

    private uint? _max_times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"max_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint max_times
    {
      get { return _max_times?? default(uint); }
      set { _max_times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool max_timesSpecified
    {
      get { return _max_times != null; }
      set { if (value == (_max_times== null)) _max_times = value ? max_times : (uint?)null; }
    }
    private bool ShouldSerializemax_times() { return max_timesSpecified; }
    private void Resetmax_times() { max_timesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProbType")]
    public enum ProbType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROB_TYPE_EQUAL", Value=1)]
      PROB_TYPE_EQUAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROB_TYPE_SPECIFIED", Value=2)]
      PROB_TYPE_SPECIFIED = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Range")]
  public partial class Range : global::ProtoBuf.IExtensible
  {
    public Range() {}
    

    private TABLE.Range.RangeType? _range_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"range_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public TABLE.Range.RangeType range_type
    {
      get { return _range_type?? TABLE.Range.RangeType.RANGE_TYPE_INVALID; }
      set { _range_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool range_typeSpecified
    {
      get { return _range_type != null; }
      set { if (value == (_range_type== null)) _range_type = value ? range_type : (TABLE.Range.RangeType?)null; }
    }
    private bool ShouldSerializerange_type() { return range_typeSpecified; }
    private void Resetrange_type() { range_typeSpecified = false; }
    

    private uint? _lhs;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lhs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lhs
    {
      get { return _lhs?? default(uint); }
      set { _lhs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lhsSpecified
    {
      get { return _lhs != null; }
      set { if (value == (_lhs== null)) _lhs = value ? lhs : (uint?)null; }
    }
    private bool ShouldSerializelhs() { return lhsSpecified; }
    private void Resetlhs() { lhsSpecified = false; }
    

    private uint? _rhs;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rhs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rhs
    {
      get { return _rhs?? default(uint); }
      set { _rhs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rhsSpecified
    {
      get { return _rhs != null; }
      set { if (value == (_rhs== null)) _rhs = value ? rhs : (uint?)null; }
    }
    private bool ShouldSerializerhs() { return rhsSpecified; }
    private void Resetrhs() { rhsSpecified = false; }
    
    [global::ProtoBuf.ProtoContract(Name=@"RangeType")]
    public enum RangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANGE_TYPE_INVALID", Value=0)]
      RANGE_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANGE_TYPE_CLOSED_CLOSED", Value=1)]
      RANGE_TYPE_CLOSED_CLOSED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANGE_TYPE_CLOSED_OPEN", Value=2)]
      RANGE_TYPE_CLOSED_OPEN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANGE_TYPE_OPEN_CLOSED", Value=3)]
      RANGE_TYPE_OPEN_CLOSED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANGE_TYPE_OPEN_OPEN", Value=4)]
      RANGE_TYPE_OPEN_OPEN = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityAwardList")]
  public partial class ActivityAwardList : global::ProtoBuf.IExtensible
  {
    public ActivityAwardList() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.ActivityAwardList.ActivityAward> _award = new global::System.Collections.Generic.List<TABLE.ActivityAwardList.ActivityAward>();
    [global::ProtoBuf.ProtoMember(1, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.ActivityAwardList.ActivityAward> award
    {
      get { return _award; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityAward")]
  public partial class ActivityAward : global::ProtoBuf.IExtensible
  {
    public ActivityAward() {}
    

    private uint? _item_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_id
    {
      get { return _item_id?? default(uint); }
      set { _item_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool item_idSpecified
    {
      get { return _item_id != null; }
      set { if (value == (_item_id== null)) _item_id = value ? item_id : (uint?)null; }
    }
    private bool ShouldSerializeitem_id() { return item_idSpecified; }
    private void Resetitem_id() { item_idSpecified = false; }
    

    private uint? _item_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_count
    {
      get { return _item_count?? default(uint); }
      set { _item_count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool item_countSpecified
    {
      get { return _item_count != null; }
      set { if (value == (_item_count== null)) _item_count = value ? item_count : (uint?)null; }
    }
    private bool ShouldSerializeitem_count() { return item_countSpecified; }
    private void Resetitem_count() { item_countSpecified = false; }
    

    private uint? _lev;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lev
    {
      get { return _lev?? default(uint); }
      set { _lev = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levSpecified
    {
      get { return _lev != null; }
      set { if (value == (_lev== null)) _lev = value ? lev : (uint?)null; }
    }
    private bool ShouldSerializelev() { return levSpecified; }
    private void Resetlev() { levSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntPair")]
  public partial class IntPair : global::ProtoBuf.IExtensible
  {
    public IntPair() {}
    

    private uint? _first;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"first", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint first
    {
      get { return _first?? default(uint); }
      set { _first = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool firstSpecified
    {
      get { return _first != null; }
      set { if (value == (_first== null)) _first = value ? first : (uint?)null; }
    }
    private bool ShouldSerializefirst() { return firstSpecified; }
    private void Resetfirst() { firstSpecified = false; }
    

    private uint? _second;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint second
    {
      get { return _second?? default(uint); }
      set { _second = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool secondSpecified
    {
      get { return _second != null; }
      set { if (value == (_second== null)) _second = value ? second : (uint?)null; }
    }
    private bool ShouldSerializesecond() { return secondSpecified; }
    private void Resetsecond() { secondSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntPairList")]
  public partial class IntPairList : global::ProtoBuf.IExtensible
  {
    public IntPairList() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.IntPair> _list = new global::System.Collections.Generic.List<TABLE.IntPair>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.IntPair> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntPairList2")]
  public partial class IntPairList2 : global::ProtoBuf.IExtensible
  {
    public IntPairList2() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.IntPair> _list = new global::System.Collections.Generic.List<TABLE.IntPair>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.IntPair> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntList")]
  public partial class IntList : global::ProtoBuf.IExtensible
  {
    public IntList() {}
    
    private readonly global::System.Collections.Generic.List<int> _list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringList")]
  public partial class StringList : global::ProtoBuf.IExtensible
  {
    public StringList() {}
    
    private readonly global::System.Collections.Generic.List<string> _list = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntListJingHao")]
  public partial class IntListJingHao : global::ProtoBuf.IExtensible
  {
    public IntListJingHao() {}
    
    private readonly global::System.Collections.Generic.List<int> _list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntListXiaHuaXian")]
  public partial class IntListXiaHuaXian : global::ProtoBuf.IExtensible
  {
    public IntListXiaHuaXian() {}
    
    private readonly global::System.Collections.Generic.List<uint> _list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntListXiaHuaXianFenHao")]
  public partial class IntListXiaHuaXianFenHao : global::ProtoBuf.IExtensible
  {
    public IntListXiaHuaXianFenHao() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.IntListXiaHuaXian> _list = new global::System.Collections.Generic.List<TABLE.IntListXiaHuaXian>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.IntListXiaHuaXian> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntListJingHaoMeiYuan")]
  public partial class IntListJingHaoMeiYuan : global::ProtoBuf.IExtensible
  {
    public IntListJingHaoMeiYuan() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.IntListJingHao> _list = new global::System.Collections.Generic.List<TABLE.IntListJingHao>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.IntListJingHao> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntListList")]
  public partial class IntListList : global::ProtoBuf.IExtensible
  {
    public IntListList() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.IntList> _list = new global::System.Collections.Generic.List<TABLE.IntList>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.IntList> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntSpecXiaHuaJinHao")]
  public partial class IntSpecXiaHuaJinHao : global::ProtoBuf.IExtensible
  {
    public IntSpecXiaHuaJinHao() {}
    

    private uint? _value0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value0
    {
      get { return _value0?? default(uint); }
      set { _value0 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool value0Specified
    {
      get { return _value0 != null; }
      set { if (value == (_value0== null)) _value0 = value ? value0 : (uint?)null; }
    }
    private bool ShouldSerializevalue0() { return value0Specified; }
    private void Resetvalue0() { value0Specified = false; }
    
    private readonly global::System.Collections.Generic.List<uint> _list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntTupleList")]
  public partial class IntTupleList : global::ProtoBuf.IExtensible
  {
    public IntTupleList() {}
    
    private readonly global::System.Collections.Generic.List<TABLE.IntTupleList.IntTuple> _list = new global::System.Collections.Generic.List<TABLE.IntTupleList.IntTuple>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TABLE.IntTupleList.IntTuple> list
    {
      get { return _list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntTuple")]
  public partial class IntTuple : global::ProtoBuf.IExtensible
  {
    public IntTuple() {}
    

    private long? _first;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"first", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long first
    {
      get { return _first?? default(long); }
      set { _first = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool firstSpecified
    {
      get { return _first != null; }
      set { if (value == (_first== null)) _first = value ? first : (long?)null; }
    }
    private bool ShouldSerializefirst() { return firstSpecified; }
    private void Resetfirst() { firstSpecified = false; }
    

    private long? _second;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long second
    {
      get { return _second?? default(long); }
      set { _second = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool secondSpecified
    {
      get { return _second != null; }
      set { if (value == (_second== null)) _second = value ? second : (long?)null; }
    }
    private bool ShouldSerializesecond() { return secondSpecified; }
    private void Resetsecond() { secondSpecified = false; }
    

    private long? _third;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"third", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long third
    {
      get { return _third?? default(long); }
      set { _third = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool thirdSpecified
    {
      get { return _third != null; }
      set { if (value == (_third== null)) _third = value ? third : (long?)null; }
    }
    private bool ShouldSerializethird() { return thirdSpecified; }
    private void Resetthird() { thirdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}