//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: role.proto
namespace roleV2
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResPlayerBasicInfo")]
  public partial class ResPlayerBasicInfo : global::ProtoBuf.IExtensible
  {
    public ResPlayerBasicInfo() {}
    

    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private long? _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId?? default(long); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return _roleId != null; }
      set { if (value == (_roleId== null)) _roleId = value ? roleId : (long?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<roleV2.PlayerAttribute> _attr = new global::System.Collections.Generic.List<roleV2.PlayerAttribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<roleV2.PlayerAttribute> attr
    {
      get { return _attr; }
    }
  

    private int? _x;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x?? default(int); }
      set { _x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xSpecified
    {
      get { return _x != null; }
      set { if (value == (_x== null)) _x = value ? x : (int?)null; }
    }
    private bool ShouldSerializex() { return xSpecified; }
    private void Resetx() { xSpecified = false; }
    

    private int? _y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y?? default(int); }
      set { _y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ySpecified
    {
      get { return _y != null; }
      set { if (value == (_y== null)) _y = value ? y : (int?)null; }
    }
    private bool ShouldSerializey() { return ySpecified; }
    private void Resety() { ySpecified = false; }
    

    private int? _z;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z?? default(int); }
      set { _z = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool zSpecified
    {
      get { return _z != null; }
      set { if (value == (_z== null)) _z = value ? z : (int?)null; }
    }
    private bool ShouldSerializez() { return zSpecified; }
    private void Resetz() { zSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAttribute")]
  public partial class PlayerAttribute : global::ProtoBuf.IExtensible
  {
    public PlayerAttribute() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"AttributeType")]
    public enum AttributeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL", Value=0)]
      NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hp", Value=1)]
      Hp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MaxHp", Value=2)]
      MaxHp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Mp", Value=3)]
      Mp = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MaxMp", Value=4)]
      MaxMp = 4
    }
  
}